{% set name = "earth2mip" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/earth2mip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a49d0607893013783d30bfcb2f80412014ab535fbcc1e96dd139b78819bd98ab

build:
  noarch: python
  script:
    - sed -i.bak '/"pytest/d' pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.10
    - altair >=4.2.2
    - cdsapi >=0.6.1
    - cfgrib >=0.9.10.3
    - cftime
    - dask >=2023.1.0
    - distributed >=2023.1.0
    - eccodes >=1.4.0
    - ecmwflibs >=0.5.2
    - einops
    - fsspec
    - h5py >=3.2.0
    - h5netcdf >=1.0.0
    - importlib-metadata >=6.7.0
    - joblib >=1.1.0
    - netcdf4 >=1.6.4
    - numpy
    - nvidia-modulus >=0.4.0
    - pandas >=1.5.3
    - properscoring >=0.1
    - pydantic >=1.10, <=1.10.11
    - python-dotenv >=1.0.0
    - s3fs
    - setuptools >=38.4
    - pytorch >=1.13
    - torch-harmonics >=0.5.0
    - tqdm >=4.65.0
    - typer
    - xarray
    - xskillscore >=0.0.24
    - zarr >=2.14.2

test:
  imports:
    - earth2mip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nvidia.github.io/earth2mip
  dev_url: https://github.com/NVIDIA/earth2mip
  summary: |
    Earth-2 Model Intercomparison Project (MIP) is a python framework that
    enables climate researchers and scientists to explore and experiment
    with AI models for weather and climate.
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
